version: "3"

services:
  eduboxbackend:
    container_name: eduboxbackend
    build: ./backend/
    command: python3 manage.py runserver 0.0.0.0:5001
    expose:
      - 5001
    ports:
      - 5001:5001
    restart: always
    env_file:
      - ./.envs/.env-dev
    volumes:
      - ./backend/:/app
    
  

    