# Generated by Django 3.1.7 on 2021-07-03 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210703_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_assignment',
        ),
        migrations.AddField(
            model_name='post',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.assignment'),
        ),
    ]
